import {
  NInput,
  NCheckbox,
  NButton,
  NRadio,
  NRadioGroup,
  NRadioButton,
  NSelect,
  NSwitch,
  NCalendar,
  NButtonGroup,
  NCheckboxGroup,
  NInputNumber,
  NSlider,
  NTimePicker,
  NTransfer,
  NCarouselItem,
  NCascader,
  NDatePicker,
} from "naive-ui";
import type { Component } from "vue";

export const components: Record<string, Component> = {
  input: NInput,
  checkbox: NCheckbox,
  button: NButton,
  radio: NRadio,
  "radio-group": NRadioGroup,
  "radio-button": NRadioButton,
  select: NSelect,
  switch: NSwitch,
  calendar: NCalendar,
  "button-group": NButtonGroup,
  "checkbox-group": NCheckboxGroup,
  "input-number": NInputNumber,
  slider: NSlider,
  "time-picker": NTimePicker,
  transfer: NTransfer,
  "carousel-item": NCarouselItem,
  cascader: NCascader,
  "date-picker": NDatePicker,
};
